#!/bin/bash

# Simple deployment script for missing ASL-LEX endpoints
# This script provides instructions for manually adding the missing endpoints

set -e

echo "🔧 Missing ASL-LEX Endpoints Deployment Guide"
echo "=============================================="
echo ""
echo "Your frontend expects these ASL-LEX endpoints that are missing from your API Gateway:"
echo ""
echo "❌ Missing Endpoints:"
echo "  - GET /api/asl-lex/statistics"
echo "  - GET /api/asl-lex/bulk-upload/template"
echo "  - GET /api/asl-lex/bulk-upload/jobs/{jobId}"
echo "  - POST /api/asl-lex/bulk-upload/jobs/{jobId}/cancel"
echo "  - POST /api/asl-lex/upload-video-with-metadata"
echo ""
echo "✅ Currently Available:"
echo "  - GET /api/asl-lex/signs"
echo "  - POST /api/asl-lex/signs"
echo "  - GET /api/asl-lex/sign-types"
echo "  - POST /api/asl-lex/sign-types"
echo "  - GET /api/asl-lex/sign-types/custom"
echo "  - POST /api/asl-lex/signs/batch-update-type"
echo "  - POST /api/asl-lex/validate-asl-sign"
echo "  - GET /api/asl-lex/analytics/sign-types"
echo "  - POST /api/asl-lex/bulk-upload"
echo "  - GET /api/asl-lex/bulk-upload/jobs"
echo ""
echo "🚀 To fix this, you have two options:"
echo ""
echo "Option 1: Use AWS Console (Recommended)"
echo "1. Go to AWS API Gateway Console"
echo "2. Select your API (qt8f7grhb5)"
echo "3. Add the missing resources and methods manually"
echo "4. Deploy the API"
echo ""
echo "Option 2: Use AWS CLI (if installed)"
echo "1. Run: chmod +x scripts/add-asl-lex-endpoints.sh"
echo "2. Update the Lambda ARN in the script"
echo "3. Run: ./scripts/add-asl-lex-endpoints.sh"
echo ""
echo "Option 3: Deploy via CloudFormation"
echo "1. Update infrastructure/api-gateway-setup.yaml"
echo "2. Deploy with: aws cloudformation deploy --template-file infrastructure/api-gateway-setup.yaml --stack-name spokhand-asl-lex-api-prod"
echo ""
echo "📋 Manual Steps for AWS Console:"
echo "1. Create resource /api/asl-lex/statistics"
echo "2. Add GET method to /api/asl-lex/statistics"
echo "3. Create resource /api/asl-lex/bulk-upload/template"
echo "4. Add GET method to /api/asl-lex/bulk-upload/template"
echo "5. Create resource /api/asl-lex/bulk-upload/jobs/{jobId}"
echo "6. Add GET method to /api/asl-lex/bulk-upload/jobs/{jobId}"
echo "7. Create resource /api/asl-lex/bulk-upload/jobs/{jobId}/cancel"
echo "8. Add POST method to /api/asl-lex/bulk-upload/jobs/{jobId}/cancel"
echo "9. Create resource /api/asl-lex/upload-video-with-metadata"
echo "10. Add POST method to /api/asl-lex/upload-video-with-metadata"
echo "11. Deploy the API"
echo ""
echo "🔗 Your API Gateway URL: https://qt8f7grhb5.execute-api.us-east-1.amazonaws.com/prod"
echo ""
echo "After adding the endpoints, your database should be visible in the Amplify app!" 