AWSTemplateFormatVersion: '2010-09-09'
Description: 'Spokhand AWS Infrastructure for Sign Language Recognition Platform'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  # S3 Bucket for video storage
  VideoStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub spokhand-videos-${Environment}
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVideos
            Status: Enabled
            ExpirationInDays: 365

  # S3 Bucket for ML models and datasets
  MLBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub spokhand-ml-${Environment}
      VersioningConfiguration:
        Status: Enabled

  # Lambda function for video processing
  VideoProcessingFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              # Video processing logic
              pass
      Runtime: python3.9
      Timeout: 300
      MemorySize: 1024

  # Lambda function for ML inference
  MLInferenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: inference.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              # ML inference logic
              pass
      Runtime: python3.9
      Timeout: 300
      MemorySize: 2048

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - !Sub arn:aws:s3:::${VideoStorageBucket}/*
                  - !Sub arn:aws:s3:::${MLBucket}/*

  # API Gateway for annotation platform
  AnnotationAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub spokhand-annotation-api-${Environment}
      Description: API for Spokhand annotation platform

  # API Gateway for ML inference
  MLAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub spokhand-ml-api-${Environment}
      Description: API for Spokhand ML inference

  # SageMaker endpoint for ML model
  MLModelEndpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName: !Ref EndpointConfig
      EndpointName: !Sub spokhand-ml-endpoint-${Environment}

  # SageMaker endpoint configuration
  EndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
        - InitialInstanceCount: 1
          InstanceType: ml.g4dn.xlarge
          ModelName: !Ref MLModel
          VariantName: AllTraffic

  # SageMaker model
  MLModel:
    Type: AWS::SageMaker::Model
    Properties:
      ModelName: !Sub spokhand-ml-model-${Environment}
      PrimaryContainer:
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/spokhand-ml:latest
        Mode: SingleModel

  # SageMaker training job
  MLTrainingJob:
    Type: AWS::SageMaker::TrainingJob
    Properties:
      TrainingJobName: !Sub spokhand-training-${Environment}
      AlgorithmSpecification:
        TrainingImage: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/spokhand-training:latest
        TrainingInputMode: File
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      InputDataConfig:
        - ChannelName: train
          DataSource:
            S3DataSource:
              S3DataType: S3Prefix
              S3Uri: !Sub s3://${MLBucket}/training/
      OutputDataConfig:
        S3OutputPath: !Sub s3://${MLBucket}/output/
      ResourceConfig:
        InstanceCount: 1
        InstanceType: ml.g4dn.xlarge
        VolumeSizeInGB: 50
      StoppingCondition:
        MaxRuntimeInSeconds: 3600

  # IAM Role for SageMaker
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

Outputs:
  VideoBucketName:
    Description: Name of the S3 bucket for video storage
    Value: !Ref VideoStorageBucket

  MLBucketName:
    Description: Name of the S3 bucket for ML models and datasets
    Value: !Ref MLBucket

  AnnotationAPIEndpoint:
    Description: API Gateway endpoint URL for annotation platform
    Value: !Sub https://${AnnotationAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}

  MLAPIEndpoint:
    Description: API Gateway endpoint URL for ML inference
    Value: !Sub https://${MLAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}

  MLModelEndpoint:
    Description: SageMaker endpoint for ML model
    Value: !GetAtt MLModelEndpoint.EndpointName 